### ISSUE TITLE
nginx-proxy and dnsproxy

### ISSUE THREAD

**Issue by manfromdownunder** [axeleroy/dnsproxy-docker#1]
Hi, and thankyou for providing an excellent starting point for using dnsproxy in docker!  i have a challenge that I am hoping you can help with as I am losing my mind trying to figure it out.

This is simply about automating certificate renewal while running dns-over-https and dns-over-tls.  Obviously nginx requires the use of port 443 and dns-over-https requires the use of port 443. So we can't use both in the stack.

So, i found some config that is used for adguardhome:

bind_host: 0.0.0.0
bind_port: 38139
tls:
  enabled: true
  server_name: yourdomain.name
  force_https: false # this lets NPM handle HTTPS
  port_https: 0 # this disables AGH's DoH server
  allow_unencrypted_doh: true # allows unencrypted comm between NPM and AGH
  certificate_path: /cert/fullchain.cer # only used for DoT
  private_key_path: /cert/yourdomain.name # only used for DoT

This allows you to disable https and allow nginx to handle it.  I can't however find any command line option to do this with dns proxy.  I can see that you can change the https port however I don't know how to implent the correct config to make it work.

Am I over complicating this? or is there a straight forward was to intergrate automatic certificate renewal?

Any help would be very much appreciated thankyou

**Comment by axeleroy** [comment]
Hello,

Yes, you can't have two containers binding to the same port, but you can get around the issue by using docker-compose's networking. It allows you to not have to expose the port on the host in order to have multiple containers communicating between them.

As I understand it, your reverse proxy is in the same docker-compose file as your dnsproxy, am I right? In this case, what I would do is 
- disable the port 443 binding for dnsproxy (ie. delete the line with `- "443:443/tcp",
- add the reverse proxy container to the network (ie. `pihole-net` in [docker-compose-pihole.yml](https://github.com/axeleroy/dnsproxy-docker/blob/main/docker-compose-pihole.yml))
- and then configure the reverse proxy to redirect traffic to `https://dnsproxy`. 
Finally I would leave the file-binding on dnsproxy to fetch the certificate for DoT (which uses its own port and thus should not create conflicts).

Using [docker-compose-pihole.yml](https://github.com/axeleroy/dnsproxy-docker/blob/main/docker-compose-pihole.yml) as an example, the updated stack should look something like that
```yml
version: '3'

services:
  pihole:
    # Nothing to change here
    ...

  unbound:
    # Nothing to change here
    ...

  dnsproxy:
    image: axeleroy/dnsproxy:latest
    container_name: dnsproxy
    depends_on:
      - pihole
    restart: unless-stopped
    ports:
      - "853:853/tcp"
      # Remove this line stops binding port 443 to the host
      # - "443:443/tcp"
    environment:
      # Nothing to change here
      ...
    volumes:
      # Nothing to change here
      ...
    networks:
      - pihole-net
    healthcheck:
      # Nothing to change here
      ...
  
  # The configuration is incomplete, I just put the relevant lines
  reverse-proxy:
    image: ...
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - pihole-net
    volumes:
    # Update accordingly to your reverse proxy's path to LetsEncrypt certificates
      - /path/to/certificates:/path/to/letsencrypt

networks:
  pihole-net:
    name: pihole-net

volumes:
  dnsmasq-d: {}
  etc-pihole: {}
  unbound-config: {}
```
